package org.smveloso.otof.gui;

import java.io.File;
import java.util.concurrent.ExecutionException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import javax.swing.UIManager;
import org.smveloso.otof.facade.FacadeException;
import org.smveloso.otof.facade.FotoFacade;

/**
 *
 * @author sergiomv
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initLookAndFeel();
        initComponents();
        fotoFacade = FotoFacade.getInstance();
    }

    private FotoFacade fotoFacade;
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabpnlMain = new javax.swing.JTabbedPane();
        pnlConsulta = new javax.swing.JPanel();
        pnlOperacao = new javax.swing.JPanel();
        pnlOpVarredura = new javax.swing.JPanel();
        btnOpVarredura = new javax.swing.JButton();
        lblOpVarreduraBaseDir = new javax.swing.JLabel();
        txtOpVarreduraBaseDir = new javax.swing.JTextField();
        btnOpVarreduraSearchBaseDir = new javax.swing.JButton();
        pnlConfig = new javax.swing.JPanel();
        pnlBottom = new javax.swing.JPanel();
        btnFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OTOF");

        javax.swing.GroupLayout pnlConsultaLayout = new javax.swing.GroupLayout(pnlConsulta);
        pnlConsulta.setLayout(pnlConsultaLayout);
        pnlConsultaLayout.setHorizontalGroup(
            pnlConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 738, Short.MAX_VALUE)
        );
        pnlConsultaLayout.setVerticalGroup(
            pnlConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        tabpnlMain.addTab("Consultas", pnlConsulta);

        pnlOpVarredura.setBorder(javax.swing.BorderFactory.createTitledBorder("Varredura"));

        btnOpVarredura.setText("Iniciar ...");
        btnOpVarredura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpVarreduraActionPerformed(evt);
            }
        });

        lblOpVarreduraBaseDir.setText("Diretório base:");

        btnOpVarreduraSearchBaseDir.setText("...");
        btnOpVarreduraSearchBaseDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpVarreduraSearchBaseDirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlOpVarreduraLayout = new javax.swing.GroupLayout(pnlOpVarredura);
        pnlOpVarredura.setLayout(pnlOpVarreduraLayout);
        pnlOpVarreduraLayout.setHorizontalGroup(
            pnlOpVarreduraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOpVarreduraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOpVarreduraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlOpVarreduraLayout.createSequentialGroup()
                        .addGap(0, 570, Short.MAX_VALUE)
                        .addComponent(btnOpVarredura, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlOpVarreduraLayout.createSequentialGroup()
                        .addComponent(lblOpVarreduraBaseDir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOpVarreduraBaseDir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOpVarreduraSearchBaseDir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlOpVarreduraLayout.setVerticalGroup(
            pnlOpVarreduraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpVarreduraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOpVarreduraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOpVarreduraBaseDir)
                    .addComponent(txtOpVarreduraBaseDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOpVarreduraSearchBaseDir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(btnOpVarredura))
        );

        javax.swing.GroupLayout pnlOperacaoLayout = new javax.swing.GroupLayout(pnlOperacao);
        pnlOperacao.setLayout(pnlOperacaoLayout);
        pnlOperacaoLayout.setHorizontalGroup(
            pnlOperacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlOpVarredura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlOperacaoLayout.setVerticalGroup(
            pnlOperacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOperacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlOpVarredura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        tabpnlMain.addTab("Operações", pnlOperacao);

        javax.swing.GroupLayout pnlConfigLayout = new javax.swing.GroupLayout(pnlConfig);
        pnlConfig.setLayout(pnlConfigLayout);
        pnlConfigLayout.setHorizontalGroup(
            pnlConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 738, Short.MAX_VALUE)
        );
        pnlConfigLayout.setVerticalGroup(
            pnlConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        tabpnlMain.addTab("Configurações", pnlConfig);

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBottomLayout = new javax.swing.GroupLayout(pnlBottom);
        pnlBottom.setLayout(pnlBottomLayout);
        pnlBottomLayout.setHorizontalGroup(
            pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBottomLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlBottomLayout.setVerticalGroup(
            pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBottomLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFechar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabpnlMain)
            .addComponent(pnlBottom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabpnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBottom, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpVarreduraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpVarreduraActionPerformed
        actionVarreduraIniciar();
    }//GEN-LAST:event_btnOpVarreduraActionPerformed

    private void btnOpVarreduraSearchBaseDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpVarreduraSearchBaseDirActionPerformed
        actionVarreduraEscolherDiretorioBase();
    }//GEN-LAST:event_btnOpVarreduraSearchBaseDirActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        actionFechar();
    }//GEN-LAST:event_btnFecharActionPerformed

    //
    // ACTIONS
    //
    
    private void actionFechar() {
        this.setVisible(false);
        this.dispose();
    }
    
    private void actionVarreduraIniciar() {
        
        //TODO validações ...
        
        try {
            File baseDir = new File(txtOpVarreduraBaseDir.getText());
            fotoFacade.executaVarredura(baseDir);
        } catch (FacadeException e) {
            String msg = e.getMessage();
            JOptionPane.showMessageDialog(this,msg,"Houve um erro",JOptionPane.ERROR_MESSAGE);
        /*
        } catch (InterruptedException | ExecutionException e) {
            //throw new FacadeException("Job interrupted or failed: " + e.getMessage());
            JOptionPane.showMessageDialog(this,e.getMessage(),"Houve um erro",JOptionPane.ERROR_MESSAGE);
        */ 
        } finally {
            
        }

    }
    
    private void actionVarreduraEscolherDiretorioBase() {
        File baseDir = guiEscolheDiretorio();
        if (null != baseDir) {            
            if (baseDir.exists() && baseDir.isDirectory()) {
                txtOpVarreduraBaseDir.setText(baseDir.getAbsolutePath());
            } else {
                guiMostraAviso("Diretório não encontrado.");
            }
        }
    }
    
    //
    // GUI STUFF
    //
    
    private File guiEscolheDiretorio() {
        File arquivo = null;
        JFileChooser chooser = new JFileChooser(new File(System.getProperty("user.dir")));
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int op = chooser.showOpenDialog(this);
        if (op == JFileChooser.APPROVE_OPTION) {
            arquivo = chooser.getSelectedFile();
        }
        return arquivo;
    }
    
    private void guiMostraAviso(String texto) {
        JOptionPane.showMessageDialog(this, texto, "Aviso", JOptionPane.INFORMATION_MESSAGE);
    }
    
    private String initLookAndFeel() {
        //log.trace(">> initLookAndFeel()");
        String lafName = UIManager.getLookAndFeel().getName();

        try {
            String systemLafName = UIManager.getSystemLookAndFeelClassName();
            //log.debug("Trying system laf: " + systemLafName);
            UIManager.setLookAndFeel(systemLafName);
        } catch (Exception e) {
            //log.warn("Could not set the LAF to native: " + e.getMessage());
        }

        //log.debug("Using LAF: " + UIManager.getLookAndFeel().getName());
        //log.trace("<< initLookAndFeel()");
        return lafName;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnOpVarredura;
    private javax.swing.JButton btnOpVarreduraSearchBaseDir;
    private javax.swing.JLabel lblOpVarreduraBaseDir;
    private javax.swing.JPanel pnlBottom;
    private javax.swing.JPanel pnlConfig;
    private javax.swing.JPanel pnlConsulta;
    private javax.swing.JPanel pnlOpVarredura;
    private javax.swing.JPanel pnlOperacao;
    private javax.swing.JTabbedPane tabpnlMain;
    private javax.swing.JTextField txtOpVarreduraBaseDir;
    // End of variables declaration//GEN-END:variables
}
