package org.smveloso.otof.gui;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import org.smveloso.otof.facade.FacadeException;
import org.smveloso.otof.facade.PhotoFacade;
import org.smveloso.otof.model.LocalFileSystemAlbum;

/**
 *
 * @author sergiomv
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initLookAndFeel();
        initComponents();
        fotoFacade = PhotoFacade.getInstance();
    }

    private PhotoFacade fotoFacade;
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioGrpLimpeza = new javax.swing.ButtonGroup();
        tabpnlMain = new javax.swing.JTabbedPane();
        pnlSearch = new javax.swing.JPanel();
        pnlAlbum = new javax.swing.JPanel();
        pnlOpUpdateAlbum = new javax.swing.JPanel();
        btnOpUpdateAlbum = new javax.swing.JButton();
        lblOpUpdateAlbumBaseDir = new javax.swing.JLabel();
        txtOpUpdateAlbumBaseDir = new javax.swing.JTextField();
        btnOpUpdateAlbumSearchBaseDir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        pnlBottom = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OTOF");

        javax.swing.GroupLayout pnlSearchLayout = new javax.swing.GroupLayout(pnlSearch);
        pnlSearch.setLayout(pnlSearchLayout);
        pnlSearchLayout.setHorizontalGroup(
            pnlSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 748, Short.MAX_VALUE)
        );
        pnlSearchLayout.setVerticalGroup(
            pnlSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );

        tabpnlMain.addTab("Search", pnlSearch);

        pnlOpUpdateAlbum.setBorder(javax.swing.BorderFactory.createTitledBorder("Update Album"));

        btnOpUpdateAlbum.setText("Iniciar ...");
        btnOpUpdateAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpUpdateAlbumActionPerformed(evt);
            }
        });

        lblOpUpdateAlbumBaseDir.setText("Diretório base:");

        btnOpUpdateAlbumSearchBaseDir.setText("...");
        btnOpUpdateAlbumSearchBaseDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpUpdateAlbumSearchBaseDirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlOpUpdateAlbumLayout = new javax.swing.GroupLayout(pnlOpUpdateAlbum);
        pnlOpUpdateAlbum.setLayout(pnlOpUpdateAlbumLayout);
        pnlOpUpdateAlbumLayout.setHorizontalGroup(
            pnlOpUpdateAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOpUpdateAlbumLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOpUpdateAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlOpUpdateAlbumLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnOpUpdateAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlOpUpdateAlbumLayout.createSequentialGroup()
                        .addComponent(lblOpUpdateAlbumBaseDir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOpUpdateAlbumBaseDir, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOpUpdateAlbumSearchBaseDir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlOpUpdateAlbumLayout.setVerticalGroup(
            pnlOpUpdateAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpUpdateAlbumLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlOpUpdateAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOpUpdateAlbumBaseDir)
                    .addComponent(txtOpUpdateAlbumBaseDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOpUpdateAlbumSearchBaseDir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOpUpdateAlbum))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Available Albums"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlAlbumLayout = new javax.swing.GroupLayout(pnlAlbum);
        pnlAlbum.setLayout(pnlAlbumLayout);
        pnlAlbumLayout.setHorizontalGroup(
            pnlAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAlbumLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlOpUpdateAlbum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlAlbumLayout.setVerticalGroup(
            pnlAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAlbumLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlOpUpdateAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(261, Short.MAX_VALUE))
        );

        tabpnlMain.addTab("Album", pnlAlbum);

        pnlBottom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnClose.setText("Close Window");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBottomLayout = new javax.swing.GroupLayout(pnlBottom);
        pnlBottom.setLayout(pnlBottomLayout);
        pnlBottomLayout.setHorizontalGroup(
            pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBottomLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlBottomLayout.setVerticalGroup(
            pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBottomLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabpnlMain)
            .addComponent(pnlBottom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabpnlMain)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        actionFechar();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnOpUpdateAlbumSearchBaseDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpUpdateAlbumSearchBaseDirActionPerformed
        actionVarreduraEscolherDiretorioBase();
    }//GEN-LAST:event_btnOpUpdateAlbumSearchBaseDirActionPerformed

    private void btnOpUpdateAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpUpdateAlbumActionPerformed
        actionVarreduraIniciar();
    }//GEN-LAST:event_btnOpUpdateAlbumActionPerformed

    //
    // ACTIONS
    //
    
    private void actionFechar() {
        this.setVisible(false);
        this.dispose();
    }
    
    private void actionVarreduraIniciar() {
        
        //TODO validações ...
        
        try {
            //File baseDir = new File(txtOpVarreduraBaseDir.getText());
            LocalFileSystemAlbum localFsAlbum = new LocalFileSystemAlbum();
            fotoFacade.performAlbumUpdate(localFsAlbum);
        } catch (FacadeException e) {
            String msg = e.getMessage();
            JOptionPane.showMessageDialog(this,msg,"Houve um erro",JOptionPane.ERROR_MESSAGE);
        /*
        } catch (InterruptedException | ExecutionException e) {
            //throw new FacadeException("Job interrupted or failed: " + e.getMessage());
            JOptionPane.showMessageDialog(this,e.getMessage(),"Houve um erro",JOptionPane.ERROR_MESSAGE);
        */ 
        } finally {
            
        }

    }
    
    private void actionVarreduraEscolherDiretorioBase() {
        File baseDir = guiEscolheDiretorio();
        if (null != baseDir) {            
            if (baseDir.exists() && baseDir.isDirectory()) {
                txtOpUpdateAlbumBaseDir.setText(baseDir.getAbsolutePath());
            } else {
                guiMostraAviso("Diretório não encontrado.");
            }
        }
    }
    
    //
    // GUI STUFF
    //
    
    private File guiEscolheDiretorio() {
        File arquivo = null;
        JFileChooser chooser = new JFileChooser(new File(System.getProperty("user.dir")));
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int op = chooser.showOpenDialog(this);
        if (op == JFileChooser.APPROVE_OPTION) {
            arquivo = chooser.getSelectedFile();
        }
        return arquivo;
    }
    
    private File guiEscolheArquivo() {
        File arquivo = null;
        JFileChooser chooser = new JFileChooser(new File(System.getProperty("user.dir")));
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int op = chooser.showOpenDialog(this);
        if (op == JFileChooser.APPROVE_OPTION) {
            arquivo = chooser.getSelectedFile();
        }
        return arquivo;
    }
    
    
    private void guiMostraAviso(String texto) {
        JOptionPane.showMessageDialog(this, texto, "Aviso", JOptionPane.INFORMATION_MESSAGE);
    }
    
    private String initLookAndFeel() {
        //log.trace(">> initLookAndFeel()");
        String lafName = UIManager.getLookAndFeel().getName();

        try {
            String systemLafName = UIManager.getSystemLookAndFeelClassName();
            //log.debug("Trying system laf: " + systemLafName);
            UIManager.setLookAndFeel(systemLafName);
        } catch (Exception e) {
            //log.warn("Could not set the LAF to native: " + e.getMessage());
        }

        //log.debug("Using LAF: " + UIManager.getLookAndFeel().getName());
        //log.trace("<< initLookAndFeel()");
        return lafName;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnOpUpdateAlbum;
    private javax.swing.JButton btnOpUpdateAlbumSearchBaseDir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblOpUpdateAlbumBaseDir;
    private javax.swing.JPanel pnlAlbum;
    private javax.swing.JPanel pnlBottom;
    private javax.swing.JPanel pnlOpUpdateAlbum;
    private javax.swing.JPanel pnlSearch;
    private javax.swing.ButtonGroup radioGrpLimpeza;
    private javax.swing.JTabbedPane tabpnlMain;
    private javax.swing.JTextField txtOpUpdateAlbumBaseDir;
    // End of variables declaration//GEN-END:variables
}
