#!/bin/bash
docker run --rm -e THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_OTOF_DASH_PU_CONNECTION_DASH_URL='jdbc:h2:tcp://192.168.0.113:9093/otofdatabase;MVCC=true' \
	        -e THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_OTOF_DASH_PU_DRIVER_DASH_NAME='h2' \
	        -e THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_OTOF_DASH_PU_USER_DASH_NAME='sa' \
		-p 8080:8080 \
		smveloso/otof-server
